# Generated by Django 5.2.8 on 2026-04-07 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked_until',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='event_type',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('failed_login', 'Неудачный вход'), ('password_reset', 'Сброс пароля'), ('suspicious_activity', 'Подозрительная активность'), ('security_breach', 'Прорыв безопасности'), ('permission_denied', 'Отказ в доступе')], default='login', max_length=30),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['-timestamp'], name='tickets_log_timesta_08bdce_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address'], name='tickets_log_ip_addr_1a4089_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username'], name='tickets_log_usernam_2f15cc_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['is_suspicious'], name='tickets_log_is_susp_409529_idx'),
        ),
        migrations.DeleteModel(
            name='SecurityLog',
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
