# Generated by Django 5.2 on 2026-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_securitylog_user_remove_useractionlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblock_at', models.DateTimeField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('reason', models.CharField(default='Много неудачных попыток входа', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IP Block',
                'verbose_name_plural': 'IP Blocks',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['ip_address'], name='tickets_ipb_ip_addr_949b48_idx'), models.Index(fields=['is_active'], name='tickets_ipb_is_acti_823a3f_idx'), models.Index(fields=['unblock_at'], name='tickets_ipb_unblock_becf6e_idx')],
            },
        ),
    ]
